print('Belhard!')
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print('Belhard!')
print('Belhard!')
print('Belhard!')
print('Belhard!')
print('Belhard!')
print('Belhard!')
